### ISSUE TITLE
Is there the reverse functionality?

### ISSUE THREAD

**Issue by MordorianGuy** [LinguaPhylo/LPhyBeast#117]
Is there the possibility to convert already existing **XML**-model to *LPhy*?

**Comment by walterxie** [comment]
Simple answer is no. But you can use lphy studio to configure the model.

**Comment by MordorianGuy** [comment]
> The simple answer is "no" at the moment. But assuming you know the model in XML, you can use lphy studio to configure the model, and then use LPhy BEAST to create the XML.

Thank you for the answer! Yes, I know; just have had a little hope to play with my old models without constructing from scratch.
