### ISSUE TITLE
change constants in command line arguments 

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#124]
parameterize the constants like that using macros or command line arguments

**Comment by alexeid** [comment]
Not sure about this solution. Then there will not be a connection between the lphy file and the actual simulations without know what the command line was. Looking just at the lphy script could be misleading.

Another option would be to have a macro like:

`data {
    n = ${n}
    L = ${L};
   ...
}
`

or

`data {
    n = {{n}}
    L = {{L}};
   ...
}
`

Which is replaced by templating before the script is fed into the LPhy parser.

**Comment by walterxie** [comment]
The lphy script will be recorded into the top of XML with the update constant value. So no confusion, if you look at the lphy script on top of XML used for the simulation
