### ISSUE TITLE
Model misspecification test

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#137]
use the 1st lphy script to create the alignment and dates or species assigned to taxa, and take the models defined in the 2nd lphy script, then create a Xml. This is for model misspecification test.

1. validation to check the taxa names and **orders**, before copy the alignment and dates/species;
2. the alignment, the **true** values and trees are from the 1st script;
3. option to log the XML with true values

**Comment by alexeid** [comment]
Model *misspecification* test, since the model used to simulate data is different from the model used to analyze data.

**Comment by walterxie** [comment]
Swapping the value of Value<Alignment> or Value<TimeTree>  in lphy dictionary is easier than swapping sequences between two beast2 alignment.

There is an assumption : every Alignment or TimeTree in the first model (named as model 1) used to simulate data must be also in the 2nd model (named as model 2) used to analyse data. The validation will check the ID.

**Comment by alexeid** [comment]
The order won't in general be the same since the order isn't based on taxa names.
