### ISSUE TITLE
Add UpDownOperator to PopulationFunction

### ISSUE THREAD

**Issue by yxu927** [LinguaPhylo/LPhyBeast#139]
Add UpDownOperator for gompertz population and tree, where up = gompertz parameters (f0, b) and down = tree.

**Comment by walterxie** [comment]
bioDS/beast-phylonco#38f05a932b60c8ba2011597a087a1f0283f09782

**Comment by walterxie** [comment]
it is phylonco issue, move it to phylonco https://github.com/bioDS/beast-phylonco/issues/57
