### ISSUE TITLE
Operator for supporting negative values 

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#156]
From Alexei:

While looking at the LPhyBEAST code with Sebastian Hoehna we noticed that there is a bug for RealParameters in the DefaultOperatorSchedule. If the parameter comes from a Normal or Laplace distribution (or any distribution with support in negative values) the it should have a RandomWalkOperator instead of a ScaleOperator.

**Comment by walterxie** [comment]
LinguaPhylo/linguaPhylo#526

**Comment by walterxie** [comment]
I think it is solved :

`Θ ~ Normal(mean=3.0, sd=1.0);` now produces:

```xml
                <distribution id="Theta.prior" spec="distribution.Prior" x="@Theta">
                    <distr id="Normal" spec="distribution.Normal">
                        <parameter id="RealParameter1" spec="parameter.RealParameter" name="mean">3.0</parameter>
                        <parameter id="RealParameter2" spec="parameter.RealParameter" name="sigma">1.0</parameter>
                    </distr>
                </distribution>

...

<operator id="Theta.randomWalk" spec="operator.kernel.BactrianRandomWalkOperator" parameter="@Theta" scaleFactor="0.75" weight="1.0"/>

```

**Comment by alexeid** [comment]
Should there be a scale factor for a random walk? I thought it should be window size?

**Comment by walterxie** [comment]
BactrianRandomWalkOperator uses scale factor https://github.com/CompEvol/beast2/blob/master/src/beast/base/inference/operator/kernel/BactrianRandomWalkOperator.java . I have emailed Remco, and will let you know after he replies.

**Comment by walterxie** [comment]
https://github.com/CompEvol/beast2/issues/1169

**Comment by walterxie** [comment]
close this for new release. create #165 to remind updating after beast2 new release.
