### ISSUE TITLE
Update README.md with updated command and hyperlink

### ISSUE THREAD

**Issue by CSTE7007** [LinguaPhylo/LPhyBeast#157]
The section https://github.com/LinguaPhylo/LPhyBeast?tab=readme-ov-file#setup-and-usage

> Create 10 BEAST 2 XMLs for a simple [HKY+Coalescent](https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/hkyCoalescent.lphy) simulation study:
> `$BEAST_FOLDER/bin/lphybeast -r 10 examples/hkyCoalescent` 

that section currently undergoes significant changes

1. [HKY+Coalescent](https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/hkyCoalescent.lphy) hyperlink is no longer available as the file path updated  from `https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/coalescent/hkyCoalescent.lphy` to `https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/coalescent/hkyCoalescent.lphy`
2. `examples/hkyCoalescent` directory structure changed to `examples/coalescent/hkyCoalescent.lphy`
3. the file name `examples/hkyCoalescent` should be renamed `examples/coalescent/hkyCoalescent.lphy` with a (dot) `.lphy` extension.

Hence the updated section with updated hyperlink and command will be alike:

> Create 10 BEAST 2 XMLs for a simple [HKY+Coalescent](https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/coalescent/hkyCoalescent.lphy) simulation study:
> `$BEAST_FOLDER/bin/lphybeast -r 10 examples/coalescent/hkyCoalescent.lphy `

**Comment by walterxie** [comment]
Thank you for informing me. This RM is very outdated. I have directed that section to the user manual, which will be regularly updated.
