### ISSUE TITLE
Skyline plots to BEAST is broken

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#18]
`LPhyBEAST hcv.lphy`

Unhandled generator in generatorToBEAST(): ntaxa(taxa)-1;

java.lang.IllegalArgumentException: This BEASTInterface (beast.math.distributions.MarkovChainDistribution) has no input with name initialMean. Choose one of these inputs: jeffreys,reverse,uselog,shape,parameter,useLogNormal

**Comment by walterxie** [comment]
@alexeid The new code of MarkovChainDistribution https://github.com/CompEvol/beast2/commit/759566d1a937eaf14fa1f76a9cc0ce07f38cb0e7 does not exist the current beast.jar in outer-core. Do you want me to create a new beast.jar based on this new code, or move the MarkovChainDistribution to outer-core?

**Comment by alexeid** [comment]
Yes, you can add an improved MarkovChainDistribution to beast-outercore and use that instead.

**Comment by walterxie** [comment]
I have to add LogNormalDistributionModel as well, because `void setMeanAndStdDev(double mean, double stdDev)` is package-private https://github.com/CompEvol/beast2/blob/820dc4e5bfa1feac4bfa490c0a97fc48dd0b68bf/src/beast/math/distributions/LogNormalDistributionModel.java#L86-L92

**Comment by walterxie** [comment]
outercore v0.0.3 is released for this solution.
