### ISSUE TITLE
StructuredCoalescent: metadata name is number 

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#25]
This is an integration issue. TreeAnnotator does not handle metadata name as a number, such as `1[&0=0,1=1,2=0,max=0]:2.3313088944374645,` . The newick parser will throw exceptions.

However, `StructuredCoalescent` sets the meta data names by the index of unique demes: 
https://github.com/LinguaPhylo/linguaPhylo/blob/538a849abab9b764d73fa37b96c5df74fca3267e/src/lphy/evolution/coalescent/StructuredCoalescent.java#L206

The solution is to deal with this matter in `StructuredCoalescentToMascot.createTraitString`:
```
i = node.getMetaData(traitName)
IF i is Integer 
THEN replace i to unique_demes[i]
```

**Comment by alexeid** [comment]
You could also fix it in LPHY so that it produces the same kinds of trees as BEAST does...

**Comment by walterxie** [comment]
I did this in LPhyBEAST.

**Comment by alexeid** [comment]
Yes, but then LPHY will produce incompatible true trees when used as a simulator..

**Comment by walterxie** [comment]
I see. Do you want me to fix it now or after your refactor?

**Comment by alexeid** [comment]
My refactor is complete

**Comment by walterxie** [comment]
Cool

**Comment by walterxie** [comment]
Unit test failed
