### ISSUE TITLE
handle absolute path to lphy script.

### ISSUE THREAD

**Issue by bredelings** [LinguaPhylo/LPhyBeast#36]
After trying to run `bin/applauncher LPhyBEAST ~/tutorial1/RSV2.lphy`, I got:

```
picocli.CommandLine$PicocliException: Fail to read LPhy scripts from /home/bredelings/Applications/beast2/home/bredelings/tutorial1/RSV2.lphy, working path is /home/bredelings/Applications/beast2
```

It looks like something is assuming that the path to the tutorial is a relative path, and just concatenating the working directory to the front of the script path.

-BenRI

**Comment by walterxie** [comment]
The bug fix will be available in the next release.

**Comment by walterxie** [comment]
This seems to break the LPhy Studio "conversion" to set the jar "launching" (project) folder as the default working directory, which is also the parent folder of `tutorials` examples. To compromise this default and folder struture, all data path in the examples have to be a relative path like `tutorials/data/*.nex`.
When using the absolute path and without breaking this default, the user has to 
1. either update the data path in .lphy script;
2. or to define "-wd" to the parent folder of `tutorials` examples.

**Comment by walterxie** [comment]
There is inconsistent behaviour between lphy and lphybeast to handle "user.dir". This needs to resolve before continuing.

**Comment by walterxie** [comment]
LinguaPhylo /linguaPhylo#135

**Comment by walterxie** [comment]
![lbabsolute](https://user-images.githubusercontent.com/5743014/115501473-5f89f380-a2c7-11eb-995d-b5a7df065f1b.png)

![lbrelative](https://user-images.githubusercontent.com/5743014/115501477-6153b700-a2c7-11eb-81dd-ece27814279c.png)

**Comment by walterxie** [comment]
@bredelings Please check https://github.com/LinguaPhylo/LPhyBeast/releases

**Comment by bredelings** [comment]
Thanks! I will take a look....
