### ISSUE TITLE
split LPhyBeast to core and ext

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#44]
split LPhyBeast to core and extensions #40

**Comment by walterxie** [comment]
The 1st to move these to ext:
- MM (models of morphological character evolution)
- SA (Sampled ancestor trees), 
- Mascot, 
- StarBEAST2, 
- contraband bdtree.

**Comment by alexeid** [comment]
What are the BEAST-classic dependencies?

**Comment by walterxie** [comment]
BEAST-classic -> BEAST lab -> beast2

**Comment by walterxie** [comment]
#45

**Comment by walterxie** [comment]
This can be done using SPI now. But beast2 is not going to use module system, SPI has to be triggered by META-INF/services/. See one example https://github.com/LinguaPhylo/linguaPhylo/blob/master/lphy/src/main/resources/META-INF/services/lphy.spi.LPhyExtension

**Comment by walterxie** [comment]
Since BEAST 2 will neither go to module nor use SPI, we have to find another solution.

**Comment by walterxie** [comment]
Create `mascot` sub-project in `lphybeast`, and use Gradle to bundle the jars and release as a beast2 package at the moment. It can be split from lphybeast as an independent lphbeast extension in future.

**Comment by walterxie** [comment]
- MM requires to solve  #71 and make Standard data type extensible;
- SA requires to operators extensible.

**Comment by walterxie** [comment]
Create a new repo "LPhyBeastExt" containing Mascot, MM, SA.

**Comment by walterxie** [comment]
https://github.com/LinguaPhylo/LPhyBeastExt
