### ISSUE TITLE
add WeightedDirichlet prior

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#49]
add WeightedDirichlet prior:

For example, in the tutorial https://linguaphylo.github.io/tutorials/time-stamped-data/ 
```
r ~ WeightedDirichlet(conc=rep(element=1.0, times=n), weights=L); 
```
If the concentration is [1,1,1], then use the default XML. For any other concentration > 1, such as [2,2,2], then create an addition BEAST XML in the prior section for WeightedDirichlet.

**Comment by alexeid** [comment]
I think you mean for any other *concentrations*, not weights.

**Comment by walterxie** [comment]
Yes, I correct my previous words
