### ISSUE TITLE
It would be good to output the true/initial values to a Tracer compatible log file alongside the XML

### ISSUE THREAD

**Issue by alexeid** [LinguaPhylo/LPhyBeast#7]
When LPHY is generating an XML for a simulation study (i.e. data is simulated), it would be good to have the true values for all parameters output in a Tracer-compatible log file alongside the generated XML.

**Comment by walterxie** [comment]
The true values can be retrieved from `VariableLog` implemented in LPhy, and may be saved into a file `trueval.log`.
